import type {
  ReconstructionNode,
  ReconstructionSpec,
} from "@/lib/reconstruction/events";

/**
 * A small, complete, schema-valid `ReconstructionSpec` for a fictional launch
 * provider landing page. It exists so the renderer can be eyeballed at
 * `/preview` without the backend or a Grok call. The image asset id is
 * deliberately unknown (the asset route will 404) to exercise the broken-image
 * path.
 */

const SOURCE_URL = "https://spacexai.example/";

const evidence = (rationale: string) => ({
  sourceConnectionIds: [],
  confidence: 0.9,
  rationale,
});

const NODES: ReconstructionNode[] = [
  {
    id: "node_header",
    component: "HtmlElement",
    sourceElementIds: ["el_header"],
    order: 0,
    layout: {
      display: "flex",
      widthMode: "full",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 24,
    },
    props: { tag: "header" },
    evidence: evidence("Top-of-page header with brand and primary navigation."),
  },
  {
    id: "node_brand",
    component: "Text3D",
    sourceElementIds: ["el_brand"],
    parentId: "node_header",
    order: 0,
    layout: {},
    props: { text: "SPACEXAI", fontSize: 48, depth: 16, semanticTag: "h1" },
    evidence: evidence("Large brand wordmark rendered as an extruded heading."),
  },
  {
    id: "node_nav",
    component: "HtmlElement",
    sourceElementIds: ["el_nav"],
    parentId: "node_header",
    order: 1,
    layout: {},
    props: { tag: "nav", ariaLabel: "Primary" },
    evidence: evidence("Primary navigation landmark."),
  },
  {
    id: "node_nav_list",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_list"],
    parentId: "node_nav",
    order: 0,
    layout: { display: "flex", flexDirection: "row", gap: 20 },
    props: { tag: "ul" },
    evidence: evidence("Horizontal list of navigation links."),
  },
  {
    id: "node_nav_item_launches",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_item_1"],
    parentId: "node_nav_list",
    order: 0,
    layout: {},
    props: { tag: "li" },
    evidence: evidence("Navigation list item."),
  },
  {
    id: "node_nav_link_launches",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_link_1"],
    parentId: "node_nav_item_launches",
    order: 0,
    layout: {},
    props: { tag: "a", text: "Launches", href: "/launches" },
    evidence: evidence("Relative link resolved against the source origin."),
  },
  {
    id: "node_nav_item_vehicles",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_item_2"],
    parentId: "node_nav_list",
    order: 1,
    layout: {},
    props: { tag: "li" },
    evidence: evidence("Navigation list item."),
  },
  {
    id: "node_nav_link_vehicles",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_link_2"],
    parentId: "node_nav_item_vehicles",
    order: 0,
    layout: {},
    props: { tag: "a", text: "Vehicles", href: "/vehicles" },
    evidence: evidence("Relative link resolved against the source origin."),
  },
  {
    id: "node_nav_item_careers",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_item_3"],
    parentId: "node_nav_list",
    order: 2,
    layout: {},
    props: { tag: "li" },
    evidence: evidence("Navigation list item."),
  },
  {
    id: "node_nav_link_careers",
    component: "HtmlElement",
    sourceElementIds: ["el_nav_link_3"],
    parentId: "node_nav_item_careers",
    order: 0,
    layout: {},
    props: { tag: "a", text: "Careers", href: "https://careers.spacexai.example/" },
    evidence: evidence("Absolute external link."),
  },
  {
    id: "node_main",
    component: "HtmlElement",
    sourceElementIds: ["el_main"],
    order: 1,
    layout: {
      display: "flex",
      widthMode: "full",
      flexDirection: "column",
      alignItems: "center",
      gap: 32,
    },
    props: { tag: "main" },
    evidence: evidence("Main content column."),
  },
  {
    id: "node_hero_card",
    component: "Card3D",
    sourceElementIds: ["el_hero"],
    parentId: "node_main",
    order: 0,
    layout: {},
    props: { width: 780, height: 380, depth: 28 },
    evidence: evidence("Hero panel grouping the tagline and the primary actions."),
  },
  {
    id: "node_hero_copy",
    component: "TextShadow3D",
    sourceElementIds: ["el_hero_copy"],
    parentId: "node_hero_card",
    order: 0,
    layout: {},
    props: {
      text: "Reusable rockets, reconstructed in three dimensions.",
      fontSize: 22,
      semanticTag: "p",
    },
    evidence: evidence("Hero tagline, 22px display text."),
  },
  {
    id: "node_hero_actions",
    component: "Button3DGroup",
    sourceElementIds: ["el_hero_actions"],
    parentId: "node_hero_card",
    order: 1,
    layout: {},
    props: {},
    evidence: evidence("Row of three sibling call-to-action buttons."),
  },
  {
    id: "node_btn_launch",
    component: "Button3D",
    sourceElementIds: ["el_btn_launch"],
    parentId: "node_hero_actions",
    order: 0,
    layout: {},
    props: { label: "Book a launch" },
    evidence: evidence("Primary CTA linking to the booking page."),
  },
  {
    id: "node_btn_docs",
    component: "Button3D",
    sourceElementIds: ["el_btn_docs"],
    parentId: "node_hero_actions",
    order: 1,
    layout: {},
    props: { label: "Read the docs", face: "#e8dcc8", ink: "#0a0604" },
    evidence: evidence("Secondary CTA with an inverted face colour."),
  },
  {
    id: "node_btn_details",
    component: "Button3D",
    sourceElementIds: ["el_btn_details"],
    parentId: "node_hero_actions",
    order: 2,
    layout: {},
    props: { label: "Mission details" },
    evidence: evidence("Disclosure control for the details section."),
  },
  {
    id: "node_hero_image",
    component: "Image3D",
    sourceElementIds: ["el_hero_image"],
    parentId: "node_main",
    order: 1,
    layout: {},
    props: {
      assetId: "asset_000000000000000000000000",
      alt: "Falcon booster on the pad at dawn",
      width: 480,
      height: 300,
      depth: 12,
    },
    evidence: evidence("Hero photograph served from the local asset cache."),
  },
  {
    id: "node_details",
    component: "HtmlElement",
    sourceElementIds: ["el_details"],
    parentId: "node_main",
    order: 2,
    layout: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 16,
      maxWidth: 640,
      padding: 16,
    },
    props: { tag: "section", ariaLabel: "Mission details" },
    evidence: evidence("Collapsible details section toggled by the hero button."),
  },
  {
    id: "node_details_text",
    component: "TextShadow3D",
    sourceElementIds: ["el_details_text"],
    parentId: "node_details",
    order: 0,
    layout: {},
    props: {
      text: "Payload: 22,800 kg to LEO. Turnaround: 21 days.",
      fontSize: 18,
      semanticTag: "p",
    },
    evidence: evidence("Specification summary line."),
  },
  {
    id: "node_signup_form",
    component: "HtmlElement",
    sourceElementIds: ["el_form"],
    parentId: "node_details",
    order: 1,
    layout: { display: "flex", flexDirection: "row", alignItems: "center", gap: 12 },
    props: { tag: "form", action: "/subscribe", method: "post", ariaLabel: "Launch alerts" },
    evidence: evidence("Newsletter form; submission is simulated in the reconstruction."),
  },
  {
    id: "node_signup_label",
    component: "HtmlElement",
    sourceElementIds: ["el_form_label"],
    parentId: "node_signup_form",
    order: 0,
    layout: {},
    props: { tag: "label", text: "Email" },
    evidence: evidence("Field label associated with the following input."),
  },
  {
    id: "node_signup_input",
    component: "HtmlElement",
    sourceElementIds: ["el_form_input"],
    parentId: "node_signup_form",
    order: 1,
    layout: {},
    props: {
      tag: "input",
      inputType: "email",
      name: "email",
      placeholder: "you@example.com",
      required: true,
    },
    evidence: evidence("Email input."),
  },
  {
    id: "node_signup_submit",
    component: "Button3D",
    sourceElementIds: ["el_form_submit"],
    parentId: "node_signup_form",
    order: 2,
    layout: {},
    props: { label: "Notify me", buttonType: "submit", width: 140, height: 44, depth: 20 },
    evidence: evidence("Submit button for the alerts form."),
  },
  {
    id: "node_tabs",
    component: "Carousel3D",
    sourceElementIds: ["el_tabs"],
    parentId: "node_main",
    order: 3,
    layout: { widthMode: "full" },
    props: { itemCount: 4 },
    evidence: evidence("Four content tabs mapped onto a carousel ring."),
  },
  {
    id: "node_tab_overview",
    component: "TextShadow3D",
    sourceElementIds: ["el_tab_1"],
    parentId: "node_tabs",
    order: 0,
    layout: {},
    props: { text: "Overview", fontSize: 16, semanticTag: "span" },
    evidence: evidence("Tab label."),
  },
  {
    id: "node_tab_specs",
    component: "TextShadow3D",
    sourceElementIds: ["el_tab_2"],
    parentId: "node_tabs",
    order: 1,
    layout: {},
    props: { text: "Specs", fontSize: 16, semanticTag: "span" },
    evidence: evidence("Tab label."),
  },
  {
    id: "node_tab_gallery",
    component: "HtmlElement",
    sourceElementIds: ["el_tab_3"],
    parentId: "node_tabs",
    order: 2,
    layout: {},
    props: { tag: "a", text: "Gallery", href: "/gallery" },
    evidence: evidence("Tab that was a link in the source."),
  },
  {
    id: "node_tab_faq",
    component: "Button3D",
    sourceElementIds: ["el_tab_4"],
    parentId: "node_tabs",
    order: 3,
    layout: {},
    props: { label: "FAQ" },
    evidence: evidence("Tab that was a button in the source."),
  },
  {
    id: "node_back_to_top",
    component: "Icon3D",
    sourceElementIds: ["el_back_to_top"],
    parentId: "node_main",
    order: 4,
    layout: {},
    props: { name: "arrowUp", size: 44, depth: 12 },
    evidence: evidence("Back-to-top glyph."),
  },
  {
    id: "node_footer",
    component: "HtmlElement",
    sourceElementIds: ["el_footer"],
    order: 2,
    layout: {
      display: "flex",
      widthMode: "full",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 16,
      padding: 12,
    },
    props: { tag: "footer" },
    evidence: evidence("Page footer with legal text and a privacy link."),
  },
  {
    id: "node_footer_text",
    component: "TextShadow3D",
    sourceElementIds: ["el_footer_text"],
    parentId: "node_footer",
    order: 0,
    layout: {},
    props: { text: "© 2026 SpaceXAI. Simulated reconstruction.", fontSize: 16, semanticTag: "p" },
    evidence: evidence("Copyright line."),
  },
  {
    id: "node_footer_privacy",
    component: "HtmlElement",
    sourceElementIds: ["el_footer_privacy"],
    parentId: "node_footer",
    order: 1,
    layout: {},
    props: { tag: "a", text: "Privacy", href: "/legal/privacy" },
    evidence: evidence("Footer legal link."),
  },
];

export const DEMO_SPEC: ReconstructionSpec = {
  schemaVersion: "1.0",
  source: { url: SOURCE_URL, title: "SpaceXAI — Launch services" },
  page: {
    route: "/",
    title: "SpaceXAI",
    description: "Fictional launch-provider landing page used to preview the renderer.",
    maxWidth: 1200,
    padding: 32,
    gap: 40,
    theme: {
      background: "#0a0604",
      surface: "#0f1a24",
      ink: "#e8dcc8",
      accent: "#00a8ff",
      fontFamily: "var(--font-body)",
    },
  },
  nodes: NODES,
  interactions: [
    {
      id: "interaction_book_launch",
      sourceNodeId: "node_btn_launch",
      sourceConnectionIds: ["conn_btn_launch"],
      event: "click",
      action: "navigate",
      destination: "/launches/book",
      description: "Opens the launch booking page.",
    },
    {
      id: "interaction_toggle_details",
      sourceNodeId: "node_btn_details",
      targetNodeId: "node_details",
      sourceConnectionIds: ["conn_btn_details"],
      event: "click",
      action: "toggle",
      description: "Shows or hides the mission details section.",
    },
  ],
  unresolved: [],
  notes: ["Demo specification for the /preview route; not produced by the model."],
};

/** Node highlighted (with an annotation) on the /preview route. */
export const DEMO_HIGHLIGHT_NODE_ID = "node_hero_card";
